name: PRODUCT_ID
display_name: Product ID
description: The product ID. This is an internal identifier for the product, NOT the SKU.
created_at: '2026-02-24T17:12:43.357193Z'
active: true
visibility_type: normal
table_id:
- Sample Database
- PUBLIC
- ORDERS
database_type: INTEGER
base_type: type/Integer
effective_type: type/Integer
semantic_type: type/FK
database_is_auto_increment: false
database_required: false
fk_target_field_id:
- Sample Database
- PUBLIC
- PRODUCTS
- ID
dimensions:
- created_at: '2026-02-24T17:12:43.357193Z'
  entity_id: aqoaaV9goPLaQujZaH95n
  human_readable_field_id:
  - Sample Database
  - PUBLIC
  - PRODUCTS
  - TITLE
  name: Product ID
  type: external
  serdes/meta:
  - id: aqoaaV9goPLaQujZaH95n
    label: product_id
    model: Dimension
json_unfolding: false
parent_id: null
coercion_strategy: null
preview_display: true
position: 2
custom_position: 0
database_position: 2
has_field_values: null
settings: null
caveats: null
points_of_interest: null
nfc_path: null
serdes/meta:
- id: Sample Database
  model: Database
- id: PUBLIC
  model: Schema
- id: ORDERS
  model: Table
- id: PRODUCT_ID
  model: Field
database_default: null
database_indexed: true
database_is_generated: false
database_is_nullable: true
database_is_pk: null
database_partitioned: null
